#
#  This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File :
/gui/addMenu g4file G4File
/gui/addButton g4file Continue continue
/gui/addButton g4file Exit "exit"
#
/control/getEnv ALCAPWORKROOT
#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis setvis            "/control/execute {ALCAPWORKROOT}/macros/common/setvis.mac"
/control/execute {ALCAPWORKROOT}/macros/R15b_Al100.mac
#/control/execute {ALCAPWORKROOT}/macros/CheckEu152.mac
#control/execute {ALCAPWORKROOT}/macros/CheckAm241.mac

#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1"		"/run/beamOn 1"
/gui/addButton run run                  "/control/execute {ALCAPWORKROOT}/macros/run.mac"
/gui/addButton run grid_ol              "/control/execute {ALCAPWORKROOT}/macros/common/grid_ol.mac"
/gui/addButton run line_ol              "/control/execute {ALCAPWORKROOT}/macros/common/line_ol.mac"
#
# ResetMisc menu :
/gui/addMenu reset ResetMisc
/gui/addButton reset SiR2                "/control/execute {ALCAPWORKROOT}/macros/SiR2.mac"
/gui/addButton reset Al100               "/control/execute {ALCAPWORKROOT}/macros/Al100.mac"
/gui/addButton reset GeCallibration      "/control/execute {ALCAPWORKROOT}/macros/GeCallibration.mac"
/gui/addButton reset GeCalibration_Si16p_target      "/control/execute {ALCAPWORKROOT}/macros/GeCalibration_Si16p_target.mac"
/gui/addButton reset resetVerbose        "/control/execute {ALCAPWORKROOT}/macros/resetVerbose.mac"
/gui/addButton reset resetCut            "/control/execute {ALCAPWORKROOT}/macros/resetCut.mac"
/gui/addButton reset Si16p      "/control/execute {ALCAPWORKROOT}/macros/Si16p.mac"
#
# ResetOut menu :
/gui/addMenu reOut ResetOutput
/gui/addButton reOut default             "/g4sim/myAnalysisSvc/set_out_card output/output_default"
#
# ReloadGeo menu :
/gui/addMenu reGeo ReloadGeo
/gui/addButton reGeo geometry_P1         "/g4sim/det/ReloadGeo              geometry_R2015b/geometry_P1"
/gui/addButton reGeo geometry_P2         "/g4sim/det/ReloadGeo              geometry_R2015b/geometry_P2"
/gui/addButton reGeo geometry_P3         "/g4sim/det/ReloadGeo              geometry_R2015b/geometry_P3"
/gui/addButton reGeo geometry_P4         "/g4sim/det/ReloadGeo              geometry_R2015b/geometry_P4"
/gui/addButton reGeo geometry_P5         "/g4sim/det/ReloadGeo              geometry_R2015b/geometry_P5"
#
# ResetGen menu :
/gui/addMenu reGen ResetGen
/gui/addButton reGen mum_up              "/g4sim/gun/ResetGen               gen/gen_mum_up"
/gui/addButton reGen gam_tgt             "/g4sim/gun/ResetGen               gen/gen_gam_tgt"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "10 MeV"  "/gun/energy 10 MeV"
/gui/addButton gun "20 MeV"  "/gun/energy 20 MeV"
/gui/addButton gun "30 MeV"  "/gun/energy 30 MeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "mu-"     "/gun/particle mu-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#
# Gun particle position
/gui/addMenu gpos GunPosition
/gui/addButton gpos "Target"		"/gun/position 0 0 0"
/gui/addButton gpos "Off-Target"	"/gun/position 0 0 -10 mm"

# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
#/XXX/event/printModulo 100

#/vis/open OGL
#/vis/viewer/create
