#
#  This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File :
/gui/addMenu g4file G4File
/gui/addButton g4file Continue continue
/gui/addButton g4file Exit "exit"
#
/control/getEnv ALCAPWORKROOT
#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis setvis            "/control/execute {ALCAPWORKROOT}/macros/common/setvis.mac"
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run run                   "/control/execute {ALCAPWORKROOT}/macros/run.mac"
/gui/addButton run grid_ol               "/control/execute {ALCAPWORKROOT}/macros/common/grid_ol.mac"
/gui/addButton run line_ol               "/control/execute {ALCAPWORKROOT}/macros/common/line_ol.mac"
#
# ResetMisc menu :
/gui/addMenu reset ResetMisc
/gui/addButton reset SiR2                "/control/execute {ALCAPWORKROOT}/macros/SiR2.mac"
/gui/addButton reset GeCallibration      "/control/execute {ALCAPWORKROOT}/macros/GeCallibration.mac"
/gui/addButton reset GeCalibration_Si16p_target      "/control/execute {ALCAPWORKROOT}/macros/GeCalibration_Si16p_target.mac"
/gui/addButton reset resetVerbose        "/control/execute {ALCAPWORKROOT}/macros/resetVerbose.mac"
/gui/addButton reset resetCut            "/control/execute {ALCAPWORKROOT}/macros/resetCut.mac"
#
# ResetOut menu :
/gui/addMenu reOut ResetOutput
/gui/addButton reOut default             "/g4sim/myAnalysisSvc/set_out_card output/output_default"
#
# ReloadGeo menu :
/gui/addMenu reGeo ReloadGeo
/gui/addButton reGeo 1205                "/g4sim/det/ReloadGeo              geometry_1205"
/gui/addButton reGeo 1207                "/g4sim/det/ReloadGeo              geometry_1207"
/gui/addButton reGeo 1210                "/g4sim/det/ReloadGeo              geometry_1210"
/gui/addButton reGeo 1211                "/g4sim/det/ReloadGeo              geometry_1211"
/gui/addButton reGeo 1215                "/g4sim/det/ReloadGeo              geometry_1215"
/gui/addButton reGeo 1217                "/g4sim/det/ReloadGeo              geometry_1217"
/gui/addButton reGeo SiR2                "/g4sim/det/ReloadGeo              geometry_SiR2"
/gui/addButton reGeo GeCallibration      "/g4sim/det/ReloadGeo              geometry_GeCalibration_Si16p_target"
#
# ResetGen menu :
/gui/addMenu reGen ResetGen
/gui/addButton reGen mum_up              "/g4sim/gun/ResetGen               gen/gen_mum_up"
/gui/addButton reGen gam_tgt             "/g4sim/gun/ResetGen               gen/gen_gam_tgt"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
/gui/addButton gun "1 GeV"   "/gun/energy 1 GeV"
/gui/addButton gun "10 GeV"  "/gun/energy 10 GeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
#/XXX/event/printModulo 100
