/control/getEnv ALCAPWORKROOT

# Get default settings
/control/execute {ALCAPWORKROOT}/macros/resetVerbose.mac
/control/execute {ALCAPWORKROOT}/macros/resetCut.mac
# Set Output
/g4sim/myAnalysisSvc/set_out_card output/output_Al100
# Set Gen
/g4sim/gun/ResetGen               gen/gen_mu_1.09

# Set Geo
/g4sim/det/ReloadGeo              geometry_R2015b/Al100

/random/setSeeds 5 6
/g4sim/myAnalysisSvc/printModulo    10000
/run/beamOn 10
