/control/getEnv ALCAPWORKROOT

# Get default settings
/control/execute {ALCAPWORKROOT}/macros/resetVerbose.mac
/control/execute {ALCAPWORKROOT}/macros/resetCut.mac
# Set Output
/g4sim/myAnalysisSvc/set_out_card output/output_default
# Set Gen
/g4sim/gun/ResetGen               gen/gen_Eu_source

# Set Geo
/g4sim/det/ReloadGeo              geometry_R2015b/geometry_GeCalibration

/random/setSeeds 5 6
/g4sim/myAnalysisSvc/printModulo    10000
/run/beamOn 10000
