/control/getEnv ALCAPWORKROOT

# Get default settings
/control/execute {ALCAPWORKROOT}/macros/resetVerbose.mac
/control/execute {ALCAPWORKROOT}/macros/resetCut.mac

# Get visualisation
/control/execute {ALCAPWORKROOT}/macros/test_vis.mac

# Set Output
/g4sim/myAnalysisSvc/set_out_card output/output_default

# Set Gen
/g4sim/gun/ResetGen               gen/gen_gam_tgt

# Set Geo
#/g4sim/det/ReloadGeo             geometry_R2013/archive/geometry_1217
/g4sim/det/ReloadGeo             geometry_R2015b/geometry_P5


#	For this run
/run/beamOn  10000

/vis/ogl/printEPS
