/control/getEnv MYG4SIMWORKROOT

# Get default settings
/control/execute {MYG4SIMWORKROOT}/macros/resetVerbose.mac
/control/execute {MYG4SIMWORKROOT}/macros/resetCut.mac

# Verbosity
#/tracking/verbose 2

# Get visualisation
/control/execute {MYG4SIMWORKROOT}/macros/andy_vis.mac

# Set Output
/g4sim/myAnalysisSvc/set_out_card output/output_default

# Set Gen
/g4sim/gun/ResetGen               gen/gen_gam_tgt

# Set Geo
/g4sim/det/ReloadGeo              geometry_1217


#	For verbose
#/tracking/verbose                  1
#/g4sim/myAnalysisSvc/printModulo	1

#	For cutting
#/run/setCut 0.7 mm
#/stacking/setEleCut 1.5 keV
#/stacking/setPosCut 1.5 keV
#/stacking/setGamCut 1.5 keV
#/stacking/clear_white_list
#/stacking/clear_black_list
#/stacking/set_no_MC 1
#/stacking/set_no_PC 1
/stacking/set_no_sec 1

#	For generator
##/g4sim/gun/ReadCard gen_root
#/g4sim/gun/ReadCard gen_rand
#/g4sim/gun/root_filename .dummy
#/g4sim/gun/initialize

#	For this run
#/random/setSeeds 1844211379 853976860
#/g4sim/gun/root_index 2718575
#/g4sim/myAnalysisSvc/set_ofile_name output/run001.root
/run/beamOn  1

/vis/ogl/printEPS
