#
#  This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File :
/gui/addMenu g4file G4File
/gui/addButton g4file Continue continue
/gui/addButton g4file Exit "exit"
#
/control/getEnv MYG4SIMWORKROOT
#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis setvis            "/control/execute {MYG4SIMWORKROOT}/macros/common/setvis.mac"
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run run                   "/control/execute {MYG4SIMWORKROOT}/macros/run.mac"
/gui/addButton run grid_ol               "/control/execute {MYG4SIMWORKROOT}/macros/common/grid_ol.mac"
/gui/addButton run line_ol               "/control/execute {MYG4SIMWORKROOT}/macros/common/line_ol.mac"
#
# ResetMisc menu :
/gui/addMenu reset ResetMisc
/gui/addButton reset default               "/control/execute {MYG4SIMWORKROOT}/macros/default.mac"
/gui/addButton reset check                 "/control/execute {MYG4SIMWORKROOT}/macros/check.mac"
/gui/addButton reset resetVerbose          "/control/execute {MYG4SIMWORKROOT}/macros/resetVerbose.mac"
/gui/addButton reset resetCut              "/control/execute {MYG4SIMWORKROOT}/macros/resetCut.mac"
#
# ResetOut menu :
/gui/addMenu reOut ResetOutput
/gui/addButton reOut default               "/g4sim/myAnalysisSvc/set_out_card output/output_default"
#
# ReloadGeo menu :
/gui/addMenu reGeo ReloadGeo
/gui/addButton reGeo default               "/g4sim/det/ReloadGeo              geometry_default"
#
# ResetMag menu :
/gui/addMenu reMag ResetMag
/gui/addButton reMag none                  "/g4sim/det/ResetMag               mag/MagField_none"
#
# ResetGen menu :
/gui/addMenu reGen ResetGen
/gui/addButton reGen default               "/g4sim/gun/ResetGen               gen/gen_default"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
/gui/addButton gun "1 GeV"   "/gun/energy 1 GeV"
/gui/addButton gun "10 GeV"  "/gun/energy 10 GeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
#/XXX/event/printModulo 100
