/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh false
/vis/drawVolume
/vis/scene/add/trajectories smooth

/vis/viewer/clearCutawayPlanes
#/vis/viewer/addCutawayPlane 0 0 0 m -1 0 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 -1 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 0 -1
#/vis/viewer/addCutawayPlane -0.3 0.3 0 m 1 -1 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 0 -1
#/vis/viewer/set/viewpointVector 0 0 -1

#/vis/viewer/set/viewpointThetaPhi 100 -30
/vis/viewer/set/viewpointThetaPhi 260 140
/vis/viewer/set/background 1 1 1
/vis/viewer/set/culling coveredDaughters
/vis/viewer/set/edge 0
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/projection o
#/vis/viewer/set/projection p
/vis/viewer/set/style s
#/vis/viewer/set/style w

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 0.3
/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSize 0.3

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e+   red
/vis/modeling/trajectories/drawByParticleID-0/set e-   blue
/vis/modeling/trajectories/drawByParticleID-0/set p-  cyan
/vis/modeling/trajectories/drawByParticleID-0/set p+  cyan
/vis/modeling/trajectories/drawByParticleID-0/set pi-  yellow
/vis/modeling/trajectories/drawByParticleID-0/set pi+  yellow
/vis/modeling/trajectories/drawByParticleID-0/set mu-   magenta
/vis/modeling/trajectories/drawByParticleID-0/set mu+   magenta
/vis/scene/endOfEventAction accumulate 10000000

/run/beamOn 100
/vis/ogl/printEPS
