#
#  This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File :
/gui/addMenu g4file G4File
/gui/addButton g4file Continue continue
/gui/addButton g4file Exit "exit"
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run run "/control/execute macros/run.mac"
/gui/addButton run setvis "/control/execute macros/setvis.mac"
/gui/addButton run grid_ol "/control/execute macros/grid_ol.mac"
/gui/addButton run line_ol "/control/execute macros/line_ol.mac"
/gui/addButton run coll "/control/execute macros/coll.mac"
/gui/addButton run coll.4v "/control/execute macros/coll.4v.mac"
/gui/addButton run cdchit "/control/execute macros/cdchit.mac"
/gui/addButton run cdchit.4v "/control/execute macros/cdchit.4v.mac"
/gui/addButton run cdctrack.4v "/control/execute macros/cdctrack.4v.mac"
/gui/addButton run TriCt.4v "/control/execute macros/TriCt.4v.mac"
/gui/addButton run b9 "/control/execute macros/b9.mac"
/gui/addButton run b9.4v "/control/execute macros/b9.4v.mac"
/gui/addButton run reflect "/control/execute macros/reflect.mac"
/gui/addButton run CP1 "/control/execute macros/COMETPhaseI.mac"
/gui/addButton run alcap "/control/execute macros/alcap.mac"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
/gui/addButton gun "1 GeV"   "/gun/energy 1 GeV"
/gui/addButton gun "10 GeV"  "/gun/energy 10 GeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis DAWNFILE  "/control/execute macros/visTutor/Vis0.mac"
/gui/addButton vis OpenInventor "/control/execute macros/visTutor/Vis5.mac"
/gui/addButton vis TimeSlicing "/control/execute macros/visTutor/Vis12.mac"
/gui/addButton vis EmShower "/control/execute macros/visTutor/Vis13.mac"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
#/XXX/event/printModulo 100
