/vis/viewer/clearCutawayPlanes
#/vis/viewer/addCutawayPlane 0 0 0 m -1 0 0
/vis/viewer/addCutawayPlane 0 0 0 m 0 -1 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 0 -1
#/vis/viewer/addCutawayPlane -0.3 0.3 0 m 1 -1 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 0 -1
#/vis/viewer/set/viewpointVector 0 0 -1
/vis/viewer/set/viewpointThetaPhi 180 0 deg
/vis/viewer/set/background 1 1 1
/vis/viewer/set/culling coveredDaughters
/vis/viewer/set/edge 0
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/projection o
#/vis/viewer/set/projection p
/vis/viewer/set/style s
#/vis/viewer/set/style w
