/vis/viewer/clearCutawayPlanes
#/vis/viewer/addCutawayPlane 0 0 0 m -1 0 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 -1 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 0 -1
#/vis/viewer/addCutawayPlane -0.3 0.3 0 m 1 -1 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 0 -1
#/vis/viewer/addCutawayPlane 0 0 0 m 0 1 0
#/vis/viewer/set/viewpointVector 0 0 -1

/vis/viewer/zoom 2.4

/vis/viewer/set/viewpointThetaPhi 0 0
#/vis/viewer/set/viewpointThetaPhi 300 -20
#/vis/viewer/set/viewpointThetaPhi 270 0  

#/vis/viewer/set/lightsThetaPhi 90 180

/vis/viewer/set/background 1 1 1
/vis/viewer/set/culling coveredDaughters
/vis/viewer/set/edge 0
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/projection o
#/vis/viewer/set/projection p
/vis/viewer/set/style s
#/vis/viewer/set/style w

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true

#/vis/filtering/trajectories/create/attributeFilter
#/vis/filtering/trajectories/attributeFilter-0/setAttribute fGlobalTime
#/vis/filtering/trajectories/attributeFilter-0/addInterval 0~100

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 0.3
/vis/modeling/trajectories/drawByParticleID-0/set e+   red
/vis/modeling/trajectories/drawByParticleID-0/set e-   blue
/vis/modeling/trajectories/drawByParticleID-0/set p-  cyan
/vis/modeling/trajectories/drawByParticleID-0/set p+  cyan
/vis/modeling/trajectories/drawByParticleID-0/set pi-  yellow
/vis/modeling/trajectories/drawByParticleID-0/set pi+  yellow
/vis/modeling/trajectories/drawByParticleID-0/set mu-   magenta
/vis/modeling/trajectories/drawByParticleID-0/set mu+   magenta
/vis/scene/endOfEventAction accumulate 10000000

/stacking/setEleCut 1.5 keV
/stacking/setPosCut 1.5 keV
/stacking/setGamCut 1.5 keV
/stacking/clear_white_list
/stacking/clear_black_list
/stacking/set_no_sec 1
/stacking/set_no_MC 1
/stacking/set_no_PC 1
/run/setCut 0.001 mm
/g4sim/event/printModulo            1
