/control/verbose                    2
/persistency/verbose                3
/geometry/navigator/verbose         4
/tracking/verbose                   5
/event/verbose                      2
/event/stack/verbose                2
/cuts/verbose                       3
/run/verbose                        2
/run/particle/verbose               3
#/particle/verbose                   0
#/particle/property/verbose          0
#/particle/process/verbose           1   -1
/process/verbose                    1
/material/verbose                   1
#/tracking/verbose                    1
/g4sim/event/printModulo      1
